version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: influencer-db
    environment:
      POSTGRES_USER: virajpatel
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sponsorship_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: influencer-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sponsorship_db
      SPRING_DATASOURCE_USERNAME: virajpatel
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: